### PR TITLE
Fix routing for 404 not found.

### PR DESCRIPTION
**Pull request by lennerd**
The `routeInformation` is `null` when the given route does not match the URL format. Detecting a 404 based on the URL format might not be a save way of detecting a 404 but should be sufficient for a first version.

Also I think the 404 error page looks a bit broken on desktop. Not sure if I should fix this with this PR, too?

screenshot 2018-09-13 10 48 36

### CODE REVIEW

**Comment by opyh** [comment]
@lennerd Yeah, a very simple design for the desktop version would be cool to have as part if this PR. This still looks too broken to show it to someone.

**Comment by dakeyras7** [comment]
Code lgtm 👍🏼

**Comment by lennerd** [comment]
What do you think?

screenshot 2018-09-13 13 40 31

**Comment by opyh** [comment]
I think it's great! :)

**Pull request merged**
